### ISSUE TITLE
Max Frame Items?

### ISSUE THREAD

**Issue by gngrwzrd** [djacobs/PyAPNs#113]
Do you know what type of maximum limit should be put in frames?

I don't have thousands of devices to test with at the moment, so I'm not 100% sure how to handle maximum amount of items in the frame.

Would it make sense to stuff as many as possible into a frame? What if I have 5K devices?

Or would it work to say only allow 500 per frame, send when it's full, then create a new frame and send those? 

Would I ever need to reconnect the APNS connection?

Sorry this is more of a question not necessarily a bug..

**Comment by jimhorng** [comment]
@gngrwzrd 
Suggest you can do maximum frame test for the community, you can wrap messages in frames to the same device, yeah?

> Would I ever need to reconnect the APNS connection?
You should NOT have to, PyAPNs will do it for you, unless you encounter some wired problems. :)

**Comment by geeknam** [comment]
I have 33k tokens and looks like PyAPNs doesn't send to all of them (if I chunk it in 200, it works). I also have a cleaning task that runs every 2 hours to wiped the failed tokens.
