### ISSUE TITLE
[Errno 336265218] _ssl.c:355: error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib

### ISSUE THREAD

**Issue by mrgaolei** [djacobs/PyAPNs#118]
OS:Gentoo
Python:2.7.7

send notification directly every thing are OK.
But under Django environment, prompt the error:

[Errno 336265218] _ssl.c:355: error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib
Request Method:	POST
Request URL:	https://push.fmit.cn/admin/main/pmsg/
Django Version:	1.6.10
Exception Type:	SSLError
Exception Value:	
[Errno 336265218] _ssl.c:355: error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib
Exception Location:	/usr/lib64/python2.7/ssl.py in __init__, line 146
Python Executable:	/usr/bin/uwsgi
Python Version:	2.7.7
Python Path:	
['.',
 '',
 '/usr/lib64/python2.7/site-packages/pytz-2014.10-py2.7.egg',
 '/usr/lib64/python2.7/site-packages/pyparsing-2.0.3-py2.7.egg',
 '/usr/lib64/python2.7/site-packages/django_xmlrpc-0.1.5-py2.7.egg',
 '/usr/lib64/python2.7/site-packages/django_tagging-0.3.4-py2.7.egg',
 '/usr/lib64/python2.7/site-packages/django_mptt-0.6.1-py2.7.egg',
 '/usr/lib64/python2.7/site-packages/django_contrib_comments-1.5-py2.7.egg',
 '/usr/lib64/python2.7/site-packages/beautifulsoup4-4.3.2-py2.7.egg',
 '/usr/lib64/python2.7/site-packages/django_blog_zinnia-0.14.3-py2.7.egg',
 '/usr/lib64/python2.7/site-packages/oss-0.3.6-py2.7.egg',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages']

**Comment by denisov** [comment]
Hi!

Check your certificate. Is it available in your Django environment?

**Comment by mrgaolei** [comment]
Which certificate should I check?
Apple Push Notification? or System CA?
Check for what? Readable for Django run user?

**Comment by Charybdis** [comment]
Late reply, but I ran into this issue also. Django probably isn't finding your cert/key files. The last comment here worked for me: https://github.com/djacobs/PyAPNs/issues/12

**Comment by ridwankazi** [comment]
I am getting this same error. Any advice on what I should check about Cert file or the Key file.

**Comment by clint74** [comment]
After a long headache I found the solution. Use full path.
apns = APNs(use_sandbox=False, cert_file='/opt/producao/djangosys/prod_cert.pem', key_file='/opt/producao/djangosys/prod_key.pem')

**Comment by MrCsabaToth** [comment]
I have the same trouble.

**Comment by MrCsabaToth** [comment]
It was just a non existent pem file in my case :P
