### ISSUE TITLE
Cannot start app.py

### ISSUE THREAD

**Issue by alexrv0922** [djacobs/PyAPNs#126]
Hi there I'm trying to run the example from the main page and I keep getting this error:

  from apns import *
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/apns.py", line 218
    except ssl.SSLError, err:
                       ^
SyntaxError: invalid syntax

Process finished with exit code 1

**Comment by jimhorng** [comment]
Hi @alexrv0922 , not yet support python 3, #85 , FYR.

**Comment by hyunsoogo** [comment]
@alexrv0922 
You may start script, if you change 
ssl.SSLError, err
to
ssl.SSLError as err

**Comment by codepython** [comment]
that is python2 and python3 uncompitable problems

**Comment by ExplodingCabbage** [comment]
The syntax error described here has been fixed. I'm going to close this and try to channel any further discussion about Python 3 compatibility into this issue: https://github.com/djacobs/PyAPNs/issues/85
