### ISSUE TITLE
Exception AttributeError: "'NoneType' object has no attribute 'info'" in <bound method GatewayConnection.__del__ of <apns.GatewayConnection object

### ISSUE THREAD

**Issue by riegie** [djacobs/PyAPNs#131]
Currently using Gunicorn to run my application via Django. Every time I terminate the Gunicorn process, this exception comes up.

**Comment by alarin** [comment]
have the same problem

**Comment by puneetkaura** [comment]
I also have the same problem ??

**Comment by ExplodingCabbage** [comment]
Since @djacobs has decided to merge https://github.com/djacobs/PyAPNs/pull/138, for better or worse, this is fixed.
