### ISSUE TITLE
How to send notification to multiple device at a time.

### ISSUE THREAD

**Issue by amankumarjain** [djacobs/PyAPNs#136]
Using 'send_notification' method is their any way to send multiple notification by passing list of device_token or do we have to go through loop?... Please help me here.

**Comment by MaximilianoRios** [comment]
Unfortunately, there's not any method to do it, push notifications at least at this moment are single messages.

**Comment by amankumarjain** [comment]
okie... i find out the best way to doit.. thanks

**Comment by harshatba** [comment]
@amankumarjain Can you please tell whats the method to sned multiple notifications?
