### ISSUE TITLE
alert property title

### ISSUE THREAD

**Issue by gensmusic** [djacobs/PyAPNs#139]
I see docs  in apple development  website, https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

alert has an property title, but PayloadAlert doesn't have it.

**Comment by gensmusic** [comment]
the repo is no longer maintained ????

**Comment by gensmusic** [comment]
OK. I solve this by inherit PayloadAlert myself.

**Comment by iAnanich** [comment]
@gensmusic Could you please share your code or make a PullRequest?
