### ISSUE TITLE
_sent_notifications needs to be initialized for enchanced=False

### ISSUE THREAD

**Issue by kaansoral** [djacobs/PyAPNs#149]
with Frame'd notifications, self._sent_notifications is referenced/used, yet it's not initialized, so multiple notifications fail

I initialized it myself, yet I'm not sure whether it was the right way to do it

**Comment by farridav** [comment]
AFAICT this is resolved here https://github.com/djacobs/PyAPNs/commit/1842c40d8b9586643097c9ad142c5e447408d14f
