### ISSUE TITLE
I installed 2.0.1 using easy_install and I get an error on import

### ISSUE THREAD

**Issue by andytriboletti** [djacobs/PyAPNs#151]
I am running the sample code and I get this error:

Traceback (most recent call last):
  File "apns.py", line 2, in <module>
    from apns import apns, Frame, Payload
  File "/home/bitnami/yesorno-python/apns.py", line 2, in <module>
    from apns import apns, Frame, Payload
ImportError: cannot import name apns

**Comment by ozgur** [comment]
You should change your file name `apns.py` to something else such as `push.py`.
