### ISSUE TITLE
DeprecationWarning: integer argument expected, got float

### ISSUE THREAD

**Issue by ChristianVirtual** [djacobs/PyAPNs#158]
when running APNS I get the first time the following messages. I read and understood I could disable the warnings but is there a fix in code available ? I tried to search first; but might have been blind. 

usr/lib/python2.6/site-packages/apns-2.0.1-py2.6.egg/apns.py:138: DeprecationWarning: integer argument expected, got float
  return pack('>I', num)

/usr/lib/python2.6/site-packages/apns-2.0.1-py2.6.egg/apns.py:517: DeprecationWarning: integer argument expected, got float
  TOKEN_LENGTH, token, len(payload), payload)

Running on a CentOS with Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56);

Else: thanks for the work; makes it really easy to work with APNS !

**Comment by veeresh24** [comment]
expiry should be an integer, you may be passing it as float.

**Comment by ChristianVirtual** [comment]
thanks; that was the right hint and pointer to fix it ...

`expiry = int(time.time()+3600)  # make it int to get rid of log message
 frame.add_item(token_hex, payload, identifier, expiry, priority)`
