### ISSUE TITLE
Not Supporting python 3

### ISSUE THREAD

**Issue by MajjigaDeepak** [djacobs/PyAPNs#166]
PyAPNs is not supporting python version 3.Getting some syntax error ^ .Could you please guide me in resolving this or any alternative ?

**Comment by AhnSeongHyun** [comment]
Fork this project and modify yourself. I did.

**Comment by MajjigaDeepak** [comment]
Thanks AhnSeognHyun,

I Forked.Could you please guide me what & where i have to modify the code?

**Comment by jakubczaplicki** [comment]
+1

**Comment by ExplodingCabbage** [comment]
Duplicate of https://github.com/djacobs/PyAPNs/issues/85
