### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by kobzar** [djacobs/PyAPNs#177]

**Comment by kobzar** [comment]
Have a lot of errors on python3.4 with str & byte convert.
Example, when i try used Frame() or feedback_server.items() a was error 

> "TypeError: Can't convert 'bytes' object to str implicitly"

For second trouble i fixed it simply:
apns.py
  ```
  def items(self):
        """
        A generator that yields (token_hex, fail_time) pairs retrieved from
        the APNs feedback server
        """
        buff = b'' #changed buff = '' to buff = b''
```
But cant fixed the same for Frame()

**Comment by kobzar** [comment]
Just change '/xx' to b'/xx'
And all working now.

**Comment by jd20** [comment]
Another Python 3 compatibility issue (tested with 3.6.0):

`  File "/Users/jason/.virtualenvs/cv/lib/python3.6/site-packages/apns.py", line 218
    except ssl.SSLError, err:
                       ^
SyntaxError: invalid syntax`

Also, not sure what version of Python 3 is supported, might be good to add that somewhere to the README.md.

**Comment by djacobs** [comment]
This is something that is in mind, but I don't have time to follow-up right now.

**Comment by ExplodingCabbage** [comment]
@jd20 the code you're quoting doesn't exist any more on the master branch, but the version of the library on PyPi is out of date (see https://github.com/djacobs/PyAPNs/issues/163). The master version from GitHub should be usable on Python 3.
