### ISSUE TITLE
New Release with Python3 optimisations

### ISSUE THREAD

**Issue by FrenchDwarf** [djacobs/PyAPNs#188]
Would it be possible to update your release, as currently using PyAPNs package from PyPI does not include the Python3 optimisation, 2.0.1 is now heavily outdated and users are forced to egg-link a github commit.

**Comment by hugollm** [comment]
Since the latest version of this repo didn't work for me on python 3 (and this seems to be an abandoned project), I switched to this one:

https://github.com/dgilland/pushjack

Worked really well for iOS notifications.

**Comment by djacobs** [comment]
@FrenchDwarf yes, I'm going to update this soon.
