### ISSUE TITLE
How to pass the pass phrase automatically?

### ISSUE THREAD

**Issue by interpegasus** [djacobs/PyAPNs#19]
Hi, currently my key.pem file has a pass phrase.

The issue happens at the following line:

apns.gateway_server.send_notification(token_hex, payload)

The script asks: Enter PEM pass phrase: and waits for user input.

I would like to know how to pass the pass phrase automatically. Is there an option for that? 

Thanks in advance!

**Comment by hussaintamboli** [comment]
Hello,

I already have a cert.pem and key.pem (with passprase). I removed the passphrase using 

    $ openssl rsa -in key.pem -out key.unencrypted.pem
    Enter pass phrase for key.pem:
    writing RSA key
    $ cat cert.pem key.unencrypted.pem > ck.pem

Then I tried to send push notification

    apns = APNs(use_sandbox=True, cert_file='ck.pem', key_file='key.unencrypted.pem')
    apns.gateway_server.send_notification(token_hex, payload)

And I get an error saying 

    ssl.SSLError: [Errno 336445449] _ssl.c:365: error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib

Did I not remove the passphrase properly?

**Comment by greentornado** [comment]
I'm having this problem too
