### ISSUE TITLE
Not supported for Python 3.6

### ISSUE THREAD

**Issue by Rajkumar55** [djacobs/PyAPNs#212]
Showing the below error
`File "/lib/python3.6/site-packages/apns.py", line 218
    except ssl.SSLError, err:
                       ^
SyntaxError: invalid syntax`

The above syntax is not supported in Python 3.6

So, it's displaying the above error even while importing APNs class.

**Comment by palto42** [comment]
The fix is to simply replace the comma with "as"

`except ssl.SSLError, err:`  -> `except ssl.SSLError as err:`

**Comment by Rajkumar55** [comment]
@palto42 Thanks.
I cloned the repo and found it.
It's working fine now.

**Comment by palto42** [comment]
The issue is that the version installed via `pip install apns` is not the same code as in this git repository although both have the same version number "2.0.1".

You can install directly from git with `pip install git+https://github.com/djacobs/PyAPNs.git`

**Comment by Rajkumar55** [comment]
@palto42 Yes. It seems so.
Will install from git. Thanks.
