### ISSUE TITLE
apns does not surport chinese 

### ISSUE THREAD

**Issue by notedit** [djacobs/PyAPNs#29]
i change the line 200  to  
```
return json.dumps(self.dict(), separators=(',',':')).encode('utf-8')  
```

it just works for me

**Comment by markmark1** [comment]
Can you please give an example of sending emoji if I use Unicode('😀😀','utf8') just gives a string of gibberish text in push not the emoji

**Comment by riegie** [comment]
@markmark1, you're close! you almost had it!:
    string = unicode('😀 ', 'utf-8')

**Comment by alphapigger** [comment]
:cry:
