### ISSUE TITLE
Update PyPI

### ISSUE THREAD

**Issue by kwellman** [djacobs/PyAPNs#63]
The version of "apns" on PyPI is old and the usage has since changed. The example in the README doesn't work with the version on PyPI even though it says that you can install the library using easy_install.

**Comment by djacobs** [comment]
We're up https://pypi.python.org/pypi/apns/2.0.1

**Comment by alliefitter** [comment]
So it's been three years, can we open this issue again? The current version on PyPi doesn't have Python 3 compatibility, and this is the only APNS package for python that has been updated in the past two years.  It looks like you uploaded to PyPi here 6879e0662cb8d3585c2888158261d4ac5fad059b and then later that day merged in a pull request for Python 3 compatibility here fce9e33c62a0cef8eebcd8b1a293d66be0b45480. Using the GitHub repository for the time being.

**Comment by djacobs** [comment]
Yes, probably we should move to requiring modern Python. But that should be a new issue, not a comment on a three year-old thread ;)
